export class Community {
    Id: number = 0;
    Name: string = '';
    Description: string = '';
    Organization: any;
    OrganizationId: number = 0;
    PriceFrom: number = 0;
    PriceTo: number = 0;
    BedFrom: number = 0;
    BedTo: number = 0;
    BathFrom: number = 0;
    BathTo: number = 0;
    AreaFrom: number = 0;
    AreaTo: number = 0;
    Location: string = '';
    Url: string ='';
    IsFeatured: boolean = false;
    IsActive: boolean = false;
    Status: string = '';
    StatusId: number = 0;
    Latitude: number = 0;
    Longitude: number = 0;
    CommunityType: string = '';
    CommunityTypeId: number = 0;
    LandArea: number = 0;
    NumberOfUnits: number = 0;
    IsPublished: boolean = false;
    CreatedDate: string = '';
};